image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - fwcd.kotlin@0.2.18:opROidxv3zxhTA9OHz3fvQ==