# use docker-compose up -d to start the network
# version 3 does not support setting memory limits for docker-compose
version: '2'
services:
  cordaptor:
    image: b180tech/cordaptor:0.1.0
    hostname: cordaptor
    mem_limit: 512m
    environment:
      - CORDA_RPC_NODE_ADDRESS=bank-node:10201 # using hostname known within the Docker network
      - CORDA_RPC_USERNAME=client # this must match build.gradle
      - CORDA_RPC_PASSWORD=test # this must match build.gradle
      # we must override Cordaptor's default of binding to the loopback interface,
      # because we want its port to be visible on the Docker network
      - CORDAPTOR_API_LISTEN_ADDRESS=0.0.0.0:8500
      # this is necessary to allow Cordaptor to generate URLs (e.g. for OpenAPI bindings or Location headers)
      # using URL resolvable outside the Docker network
      - CORDAPTOR_API_EXTERNAL_ADDRESS=localhost:9500 # this must be consistent with the ports directive below
    ports:
      - "9500:8500"
    volumes:
      # Corda RPC requires CorDapp JARs to be available in the classpath
      - ./build/libs:/cordaptor/cordapps
