# use docker-compose up -d to start the network
# version 3 does not support setting memory limits for docker-compose
version: '2'
services:
  notary-node:
    image: corda/corda-zulu-java1.8-4.5:latest
    # hostnames need to be the same as in build.gradle, because they are baked into nodeInfo files
    hostname: notary-node
    mem_limit: 1g
    expose:
      - 10200 # p2p port
      - 10201 # Corda RPC port, map to a host port using ports directive if Corda shell access is required
    volumes:
      - ./build/nodes/Notary/certificates:/opt/corda/certificates
      - ./build/nodes/Notary/cordapps:/opt/corda/cordapps
      - ./build/nodes/Notary/etc:/etc/corda
      - ./build/nodes/Notary/network-parameters:/opt/corda/network-parameters
      - ./build/nodes/Notary/logs:/opt/corda/logs
      - ./build/nodes/Notary/drivers:/opt/corda/drivers
      - ./build/nodes/Notary/persistence:/opt/corda/persistence
      - ./build/nodes/Notary/additional-node-infos:/opt/corda/additional-node-infos
      # the following makes deployNode dir layout compatible with the expectations of the docker image
      - ./build/nodes/Notary/persistence.mv.db:/opt/corda/persistence/persistence.mv.db
      - ./build/nodes/Notary/persistence.trace.db:/opt/corda/persistence/persistence.trace.db
      - ./build/nodes/Notary/node.conf:/etc/corda/node.conf
  bank-node:
    image: corda/corda-zulu-java1.8-4.5:latest
    # hostnames need to be the same as in build.gradle, because they are baked into nodeInfo files
    hostname: bank-node
    mem_limit: 1g
    expose:
      - 10200 # p2p port
      - 10201 # Corda RPC port, map to a host port using ports directive if Corda shell access is required
    volumes:
      - ./build/nodes/Bank/certificates:/opt/corda/certificates
      - ./build/nodes/Bank/cordapps:/opt/corda/cordapps
      - ./build/nodes/Bank/etc:/etc/corda
      - ./build/nodes/Bank/network-parameters:/opt/corda/network-parameters
      - ./build/nodes/Bank/logs:/opt/corda/logs
      - ./build/nodes/Bank/drivers:/opt/corda/drivers
      - ./build/nodes/Bank/persistence:/opt/corda/persistence
      - ./build/nodes/Bank/additional-node-infos:/opt/corda/additional-node-infos
      # the following makes deployNode dir layout compatible with the expectations of the docker image
      - ./build/nodes/Bank/persistence.mv.db:/opt/corda/persistence/persistence.mv.db
      - ./build/nodes/Bank/persistence.trace.db:/opt/corda/persistence/persistence.trace.db
      - ./build/nodes/Bank/node.conf:/etc/corda/node.conf
